// <auto-generated />
using System;
using Bunker.Game.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Bunker.Game.Infrastructure.Migrations
{
    [DbContext(typeof(BunkerGameDbContext))]
    [Migration("20250511123332_GameSessionWithBunker")]
    partial class GameSessionWithBunker
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Bunker.Game.Domain.AggregateModels.Bunkers.Bunker", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<Guid>("GameSessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("game_session_id");

                    b.Property<bool>("IsReadonly")
                        .HasColumnType("boolean")
                        .HasColumnName("is_readonly");

                    b.HasKey("Id")
                        .HasName("pk_bunkers");

                    b.ToTable("bunkers", (string)null);
                });

            modelBuilder.Entity("Bunker.Game.Domain.AggregateModels.Catastrophes.Catastrophe", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<Guid>("GameSessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("game_session_id");

                    b.Property<bool>("IsReadOnly")
                        .HasColumnType("boolean")
                        .HasColumnName("is_read_only");

                    b.HasKey("Id")
                        .HasName("pk_catastrophes");

                    b.ToTable("catastrophes", (string)null);
                });

            modelBuilder.Entity("Bunker.Game.Domain.AggregateModels.GameSessions.GameSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("FreeSeatsCount")
                        .HasColumnType("integer")
                        .HasColumnName("free_seats_count");

                    b.Property<string>("GameResultDescription")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("game_result_description");

                    b.Property<int>("GameState")
                        .HasColumnType("integer")
                        .HasColumnName("game_state");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_game_sessions");

                    b.ToTable("game_sessions", (string)null);
                });

            modelBuilder.Entity("Bunker.Game.Domain.AggregateModels.Bunkers.Bunker", b =>
                {
                    b.OwnsMany("Bunker.Game.Domain.AggregateModels.Bunkers.Environment", "Environments", b1 =>
                        {
                            b1.Property<Guid>("bunker_id")
                                .HasColumnType("uuid")
                                .HasColumnName("bunker_id");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer")
                                .HasColumnName("id");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<string>("Description")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("description");

                            b1.Property<bool>("IsHidden")
                                .HasColumnType("boolean")
                                .HasColumnName("is_hidden");

                            b1.HasKey("bunker_id", "Id")
                                .HasName("pk_bunker_environments");

                            b1.ToTable("bunker_environments", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("bunker_id")
                                .HasConstraintName("fk_bunker_environments_bunkers_bunker_id");
                        });

                    b.OwnsMany("Bunker.Game.Domain.AggregateModels.Bunkers.Item", "Items", b1 =>
                        {
                            b1.Property<Guid>("bunker_id")
                                .HasColumnType("uuid")
                                .HasColumnName("bunker_id");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer")
                                .HasColumnName("id");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<string>("Description")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("description");

                            b1.Property<bool>("IsHidden")
                                .HasColumnType("boolean")
                                .HasColumnName("is_hidden");

                            b1.HasKey("bunker_id", "Id")
                                .HasName("pk_bunker_items");

                            b1.ToTable("bunker_items", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("bunker_id")
                                .HasConstraintName("fk_bunker_items_bunkers_bunker_id");
                        });

                    b.OwnsMany("Bunker.Game.Domain.AggregateModels.Bunkers.Room", "Rooms", b1 =>
                        {
                            b1.Property<Guid>("bunker_id")
                                .HasColumnType("uuid")
                                .HasColumnName("bunker_id");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer")
                                .HasColumnName("id");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<string>("Description")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("description");

                            b1.Property<bool>("IsHidden")
                                .HasColumnType("boolean")
                                .HasColumnName("is_hidden");

                            b1.HasKey("bunker_id", "Id")
                                .HasName("pk_bunker_rooms");

                            b1.ToTable("bunker_rooms", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("bunker_id")
                                .HasConstraintName("fk_bunker_rooms_bunkers_bunker_id");
                        });

                    b.Navigation("Environments");

                    b.Navigation("Items");

                    b.Navigation("Rooms");
                });

            modelBuilder.Entity("Bunker.Game.Domain.AggregateModels.GameSessions.GameSession", b =>
                {
                    b.OwnsMany("Bunker.Game.Domain.AggregateModels.GameSessions.Character", "Characters", b1 =>
                        {
                            b1.Property<Guid>("game_session_id")
                                .HasColumnType("uuid")
                                .HasColumnName("game_session_id");

                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<bool>("IsKicked")
                                .HasColumnType("boolean")
                                .HasColumnName("is_kicked");

                            b1.HasKey("game_session_id", "Id")
                                .HasName("pk_game_session_characters");

                            b1.ToTable("game_session_characters", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("game_session_id")
                                .HasConstraintName("fk_game_session_characters_game_sessions_game_session_id");

                            b1.OwnsOne("Bunker.Game.Domain.AggregateModels.GameSessions.Player", "Player", b2 =>
                                {
                                    b2.Property<Guid>("Charactergame_session_id")
                                        .HasColumnType("uuid")
                                        .HasColumnName("game_session_id");

                                    b2.Property<Guid>("CharacterId")
                                        .HasColumnType("uuid")
                                        .HasColumnName("id");

                                    b2.Property<string>("Id")
                                        .IsRequired()
                                        .HasColumnType("text")
                                        .HasColumnName("player_id");

                                    b2.Property<string>("Name")
                                        .IsRequired()
                                        .HasMaxLength(100)
                                        .HasColumnType("character varying(100)")
                                        .HasColumnName("player_name");

                                    b2.HasKey("Charactergame_session_id", "CharacterId");

                                    b2.ToTable("game_session_characters");

                                    b2.WithOwner()
                                        .HasForeignKey("Charactergame_session_id", "CharacterId")
                                        .HasConstraintName("fk_game_session_characters_game_session_characters_game_sessio");
                                });

                            b1.Navigation("Player");
                        });

                    b.Navigation("Characters");
                });
#pragma warning restore 612, 618
        }
    }
}
