apiVersion: v1
kind: Service
metadata:
  name: bunker-gamecomponents-api-service
  labels:
    app: bunker-gamecomponents-api
spec:
  type: NodePort
  selector:
    app: bunker-gamecomponents-api
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080
      name: http 