deploymentMode: SingleBinary


loki:
  auth_enabled: false
  storage:
    type: filesystem
    bucketNames: {}
    s3: null
    gcs: null
    azure: null
    swift: null
    bos: null
    alibabacloud: null
  schemaConfig:
    configs:
      - from: 2025-05-01
        store: tsdb
        object_store: filesystem
        schema: v13
        index:
          prefix: loki_index_
          period: 24h
  compactor:
    compaction_interval: 10m
    retention_enabled: true
    retention_delete_delay: 2h
    retention_delete_worker_count: 150
    delete_request_store: filesystem
  limits_config:
    retention_period: 336h
    max_query_lookback: 336h 
    allow_structured_metadata: true
  commonConfig:
    path_prefix: /var/loki
    replication_factor: 1

minio:
  enabled: false

singleBinary:
  replicas: 1
  persistence:
    enabled: true
    size: 5Gi
  extraVolumes:
    - name: rules
      emptyDir: {}
  extraVolumeMounts:
    - name: rules
      mountPath: /rules

write:
  replicas: 0
read:
  replicas: 0
backend:
  replicas: 0

monitoring:
  selfMonitoring:
    enabled: false
  grafanaAgent:
    installOperator: false
lokiCanary:
  enabled: false
test:
  enabled: false
enterprise:
  enabled: false
gateway:
  enabled: false
