server:
  persistentVolume:
    size: 8Gi
  service:
    type: NodePort
    nodePort: 30900
    port: 9090
extraScrapeConfigs: |
  - job_name: 'otel-collector'
    scrape_interval: 10s
    static_configs:
      - targets: ['otel-collector-opentelemetry-collector.monitoring.svc.cluster.local:8889']
alertmanager:
  persistentVolume:
    size: 2Gi
prometheus-node-exporter:
  hostRootFsMount:
    enabled: false
