apiVersion: v1
kind: Service
metadata:
  name: bunker-game-api-service
  labels:
    app: bunker-game-api
spec:
  type: NodePort
  selector:
    app: bunker-game-api
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30081
      name: http 